[package]
name = "tinystamp"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
chrono = "0.4.37"
pretty_assertions = "1.4.0"
proptest = "1.4.0"
time = { version = "0.3.34", features = ["formatting"] }

[features]
default = ["std"]
std = []
